function createfigure(X1, Y1, Y2, Y3, Y4)
%CREATEFIGURE(X1, Y1, Y2, Y3, Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 17-Sep-2022 20:09:42

% Create figure
figure1 = figure('WindowState','maximized');

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Q_1','Parent',subplot1,'LineWidth',2,...
    'LineStyle','--',...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Heater Output (%)','FontWeight','bold');

% Create xlabel
xlabel('Time (min)','FontWeight','bold');

% Create title
title({'Temperature simulation for step input'});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 60]);
box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontSize',14,'FontWeight','bold','LineWidth',2,'XGrid','on',...
    'YGrid','on');
% Create legend
legend(subplot1,'show');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.570340909090909 0.585973961439078 0.334659090909091 0.341162790697675]);
hold(axes1,'on');

% Create plot
plot(X1,Y2,'DisplayName','T1 predicted','Parent',axes1,'LineWidth',2,...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Heater Output(%)');

% Create xlabel
xlabel('Time (min)');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[40 52]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14,'FontWeight','bold','LineWidth',2,'XGrid','on',...
    'YGrid','on');
% Create legend
legend(axes1,'show');

% Create subplot
subplot2 = subplot(2,2,3,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y3,'DisplayName','Q_2','Parent',subplot2,'LineWidth',2,...
    'LineStyle','--',...
    'Color',[1 0 0]);

% Create ylabel
ylabel('Heater Output (%)','FontWeight','bold');

% Create xlabel
xlabel('Time (min)','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 120]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[20 55]);
box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'FontSize',14,'FontWeight','bold','LineWidth',2,'XGrid','on',...
    'YGrid','on');
% Create legend
legend(subplot2,'show');

% Create subplot
subplot3 = subplot(2,2,4,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y4,'DisplayName','T2 predicted','Parent',subplot3,'LineWidth',2,...
    'Color',[1 0 0]);

% Create ylabel
ylabel('Temperature ({\circ}C)','FontWeight','bold');

% Create xlabel
xlabel('Time (min)','FontWeight','bold');

box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'FontSize',14,'FontWeight','bold','LineWidth',2,'XGrid','on',...
    'YGrid','on');
% Create legend
legend1 = legend(subplot3,'show');
set(legend1,...
    'Position',[0.807508679257913 0.36128917319058 0.098307293218871 0.0341880348757801]);

